apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm
spec:
  provider:
    gcpsm:
      projectID: solution-architect-gcp
      auth:
        workloadIdentity:
          clusterName: private-simple-bank
          clusterLocation: asia-southeast1-a
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
