apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: asia-east1-docker.pkg.dev/solution-architect-gcp/simple-bank/simple-bank:52594248e36d927f564818d7af654e3513ec4331
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.2'
              memory: '256Mi'
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 9090
              name: grpc-server
          envFrom:
            - secretRef:
                name: simple-bank-k8s-secret
      serviceAccountName: simple-bank
      restartPolicy: Always
