apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: asia-east1-docker.pkg.dev/solution-architect-gcp/simple-bank/simple-bank:90c3efd7d788600eb94e7ae0f829c4775de51bc9
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.2'
              memory: '256Mi'
            requests:
              cpu: '0.1'
              memory: '128Mi'
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 9090
              name: grpc-server
          envFrom:
            - secretRef:
                name: simple-bank-k8s-secret

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
          args:
            - '--structured-logs'
            - '--port=5432'
            - 'solution-architect-gcp:asia-east1:simplebank'
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              memory: '1Gi'
              cpu: '0.5'
            requests:
              memory: '512Mi'
              cpu: '0.2'
      serviceAccountName: simple-bank
      restartPolicy: Always
