apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: example # name of the SecretStore (or kind specified)
  target:
    name: simple-bank-secret
    creationPolicy: Owner
  data:
    - secretKey: simple-bank-secret
      remoteRef:
        key: simple-bank
