apiVersion: v1
kind: Service
metadata:
  name: sb-svc
  namespace: simple-bank
spec:
  selector:
    app: sb-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-server
      name: http-service
    - protocol: TCP
      port: 90
      targetPort: grpc-server
      name: grpc-service
  type: LoadBalancer
