apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@solution-architect-gcp.iam.gserviceaccount.com

# gcloud iam service-accounts add-iam-policy-binding \
#     external-secrets@solution-architect-gcp.iam.gserviceaccount.com \
#     --member="serviceAccount:solution-architect-gcp.svc.id.goog[external-secrets/external-secrets]" \
#     --role="roles/iam.serviceAccountTokenCreator"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-bank-private
  namespace: simple-bank
  annotations:
    iam.gke.io/gcp-service-account: simple-bank-private@solution-architect-gcp.iam.gserviceaccount.com
